/**
 * Deploys CoinFlipBetting and funds the house bankroll.
 *
 * Randomness is on-chain (block.prevrandao) — there is NO Chainlink, NO VRF
 * subscription, NO LINK. So deploying is the same one step on any network:
 *
 *   npm run deploy:local      (local Hardhat chain)
 *   npm run deploy:sepolia    (Sepolia testnet — needs .env)
 *
 * Writes public/deployment.json + public/config.js for the frontend.
 */
const fs = require("fs");
const path = require("path");
const hre = require("hardhat");

async function main() {
  const { ethers, network } = hre;
  const [deployer] = await ethers.getSigners();

  console.log(`\nNetwork:  ${network.name} (chainId ${network.config.chainId})`);
  console.log(`Deployer: ${deployer.address}`);
  console.log(`Balance:  ${ethers.formatEther(await ethers.provider.getBalance(deployer.address))} ETH\n`);

  // Treasury = fee recipient + house wallet (the "host" — that's you).
  const treasury = process.env.TREASURY_ADDRESS || "0x2F4BEF94550C29c497b999B86b758F9771F7aB39";

  console.log("→ Deploying CoinFlipBetting...");
  const Game = await ethers.getContractFactory("CoinFlipBetting");
  const game = await Game.deploy(treasury);
  await game.waitForDeployment();
  const address = await game.getAddress();
  console.log(`   CoinFlipBetting: ${address}`);
  console.log(`   treasury (fee):  ${treasury}`);

  // Pre-fund the house bankroll so visitors can play vs the house instantly.
  const houseFund = ethers.parseEther(process.env.HOUSE_FUND || "5");
  await (await game.fundHouse({ value: houseFund })).wait();
  console.log(`   house bankroll funded with ${ethers.formatEther(houseFund)} ETH.`);

  await writeConfig(game, network, treasury);
  console.log("\n✅ Done. Frontend config written to public/deployment.json\n");
}

async function writeConfig(game, network, treasury) {
  const address = await game.getAddress();
  const artifact = await hre.artifacts.readArtifact("CoinFlipBetting");
  const data = {
    address,
    chainId: network.config.chainId,
    network: network.name,
    treasury,
    abi: artifact.abi,
  };
  const publicDir = path.join(__dirname, "..", "public");
  fs.mkdirSync(publicDir, { recursive: true });
  fs.writeFileSync(path.join(publicDir, "deployment.json"), JSON.stringify(data, null, 2));
  fs.writeFileSync(
    path.join(publicDir, "config.js"),
    "// AUTO-GENERATED by scripts/deploy.js — do not edit by hand.\n" +
      "window.COINFLIP_CONFIG = " +
      JSON.stringify(data, null, 2) +
      ";\n"
  );
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
