/**
 * Writes public/contract.js with the compiled ABI + bytecode so the frontend
 * can deploy the contract straight from the browser (via MetaMask) — no CLI,
 * no scripts. Used by the static / GitHub Pages hosting.
 *
 *   npm run compile && npm run artifact
 */
const fs = require("fs");
const path = require("path");
const hre = require("hardhat");

async function main() {
  const art = await hre.artifacts.readArtifact("CoinFlipBetting");
  const out = {
    abi: art.abi,
    bytecode: art.bytecode,
    defaultTreasury: "0x2F4BEF94550C29c497b999B86b758F9771F7aB39",
  };
  const file = path.join(__dirname, "..", "public", "contract.js");
  fs.writeFileSync(
    file,
    "// AUTO-GENERATED by scripts/exportArtifact.js — ABI + bytecode for in-browser deploy.\n" +
      "window.COINFLIP_ARTIFACT = " +
      JSON.stringify(out) +
      ";\n"
  );
  console.log("Wrote public/contract.js (" + (out.bytecode.length / 2) + " bytes of bytecode)");
}

main().catch((e) => {
  console.error(e);
  process.exitCode = 1;
});
